<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PackagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('packages')->delete();
        
        \DB::table('packages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'office' => 'Flexidesk',
                'name' => 'Zero Visa License - 1 Year',
                'description' => NULL,
                'price' => '12900.00',
                'status' => 1,
                'visa_package' => 0,
                'license_validity' => 1,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:33',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'office' => 'Flexidesk',
                'name' => '1 Visa License - 1 Year',
                'description' => NULL,
                'price' => '14900.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'office' => 'Flexidesk',
                'name' => '2 Visa License - 1 Year',
                'description' => NULL,
                'price' => '16900.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'office' => 'Flexidesk',
                'name' => '3 Visa License - 1 Year',
                'description' => NULL,
                'price' => '18900.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'office' => 'Others',
                'name' => '4 Visa License - 1 Year',
                'description' => NULL,
                'price' => '20900.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'office' => 'Flexidesk',
                'name' => 'Zero Visa License - 2 Years',
                'description' => NULL,
                'price' => '21900.00',
                'status' => 1,
                'visa_package' => 0,
                'license_validity' => 2,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'office' => 'Flexidesk',
                'name' => '1 Visa License - 2 Years',
                'description' => NULL,
                'price' => '25300.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 2,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'office' => 'Flexidesk',
                'name' => '2 Visa License - 2 Years',
                'description' => NULL,
                'price' => '28700.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 2,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'office' => 'Flexidesk',
                'name' => '3 Visa License - 2 Years',
                'description' => NULL,
                'price' => '32100.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 2,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'office' => 'Others',
                'name' => '4 Visa License - 2 Years',
                'description' => NULL,
                'price' => '35500.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 2,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'office' => 'Flexidesk',
                'name' => 'Zero Visa License - 3 Years',
                'description' => NULL,
                'price' => '31000.00',
                'status' => 1,
                'visa_package' => 0,
                'license_validity' => 3,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'office' => 'Flexidesk',
                'name' => '1 Visa License - 3 Years',
                'description' => NULL,
                'price' => '35800.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 3,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'office' => 'Flexidesk',
                'name' => '2 Visa License - 3 Years',
                'description' => NULL,
                'price' => '40600.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 3,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'office' => 'Flexidesk',
                'name' => '3 Visa License - 3 Years',
                'description' => NULL,
                'price' => '45400.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 3,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'office' => 'Others',
                'name' => '4 Visa License - 3 Years',
                'description' => NULL,
                'price' => '50200.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 3,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'office' => 'Flexidesk',
                'name' => 'Zero Visa License - 5 Years',
                'description' => NULL,
                'price' => '45200.00',
                'status' => 1,
                'visa_package' => 0,
                'license_validity' => 5,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'office' => 'Flexidesk',
                'name' => '1 Visa License - 5 Years',
                'description' => NULL,
                'price' => '52200.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 5,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'office' => 'Flexidesk',
                'name' => '2 Visa License - 5 Years',
                'description' => NULL,
                'price' => '59200.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 5,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'office' => 'Flexidesk',
                'name' => '3 Visa License - 5 Years',
                'description' => NULL,
                'price' => '66200.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 5,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'office' => 'Others',
                'name' => '4 Visa License - 5 Years',
                'description' => NULL,
                'price' => '73200.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 5,
                'freezone_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2024-03-06 15:17:58',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'office' => 'Standard Office',
                'name' => 'Jafza 22, 23, 24, 25',
                'description' => NULL,
                'price' => '20000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'office' => 'NIP',
            'name' => 'National Industries Park (NIP – for NIP companies only) ',
                'description' => NULL,
                'price' => '30000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'office' => 'Warehouse',
            'name' => 'Warehouses (10 KVA-74 KVA)',
                'description' => NULL,
                'price' => '203450.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'office' => 'Executive Office',
                'name' => 'Jafza One',
                'description' => NULL,
                'price' => '54000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'office' => 'Standard Office',
                'name' => 'Jafza 22, 23, 24, 25',
                'description' => NULL,
                'price' => '20000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'office' => 'NIP',
            'name' => 'National Industries Park (NIP – for NIP companies only) ',
                'description' => NULL,
                'price' => '30000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'office' => 'Warehouse',
            'name' => 'Warehouses (10 KVA-74 KVA)',
                'description' => NULL,
                'price' => '203450.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'office' => 'Executive Office',
                'name' => 'Jafza One',
                'description' => NULL,
                'price' => '54000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'office' => 'Standard Office',
                'name' => 'Jafza 22, 23, 24, 25',
                'description' => NULL,
                'price' => '20000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'office' => 'NIP',
            'name' => 'National Industries Park (NIP – for NIP companies only) ',
                'description' => NULL,
                'price' => '30000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'office' => 'Warehouse',
            'name' => 'Warehouses (10 KVA-74 KVA)',
                'description' => NULL,
                'price' => '203450.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'office' => 'Executive Office',
                'name' => 'Jafza One',
                'description' => NULL,
                'price' => '54000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'office' => 'Standard Office',
                'name' => 'Jafza 22, 23, 24, 25',
                'description' => NULL,
                'price' => '20000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'office' => 'NIP',
            'name' => 'National Industries Park (NIP – for NIP companies only) ',
                'description' => NULL,
                'price' => '30000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'office' => 'Warehouse',
            'name' => 'Warehouses (10 KVA-74 KVA)',
                'description' => NULL,
                'price' => '203450.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'office' => 'Executive Office',
                'name' => 'Jafza One',
                'description' => NULL,
                'price' => '54000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-03-07 18:12:58',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'office' => 'Virtual Office',
                'name' => 'Business Starter - 0 Visa Package',
                'description' => NULL,
                'price' => '5499.00',
                'status' => 1,
                'visa_package' => 0,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'office' => 'Virtual Office',
                'name' => 'Business Starter - 0 Visa Package	Business Starter - 0 Visa Package',
                'description' => NULL,
                'price' => '15599.00',
                'status' => 1,
                'visa_package' => 0,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'office' => 'Virtual Office',
                'name' => 'Business Starter - 1 Visa Package - 1 Year',
                'description' => NULL,
                'price' => '13500.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'office' => 'Virtual Office',
                'name' => 'Business Starter - 1 Visa Package - 3 Year',
                'description' => NULL,
                'price' => '26605.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'office' => 'Virtual Office',
                'name' => 'Business Starter - 1 Visa Package - 5 Year',
                'description' => NULL,
                'price' => '36825.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 5,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 1 visa package',
                'description' => NULL,
                'price' => '16500.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 2 visa package',
                'description' => NULL,
                'price' => '20000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 3 visa package',
                'description' => NULL,
                'price' => '25000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 4 visa package',
                'description' => NULL,
                'price' => '29000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 1 visa package',
                'description' => NULL,
                'price' => '28050.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 2 visa package',
                'description' => NULL,
                'price' => '34000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 3 visa package',
                'description' => NULL,
                'price' => '42500.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 4 visa package',
                'description' => NULL,
                'price' => '49300.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 1 visa package',
                'description' => NULL,
                'price' => '39600.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 2 visa package',
                'description' => NULL,
                'price' => '48000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 3 visa package',
                'description' => NULL,
                'price' => '60000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 4 visa package',
                'description' => NULL,
                'price' => '69600.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 1 visa package',
                'description' => NULL,
                'price' => '49500.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 2 visa package',
                'description' => NULL,
                'price' => '60000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 3 visa package',
                'description' => NULL,
                'price' => '75000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 4 visa package',
                'description' => NULL,
                'price' => '87000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 1 visa package',
                'description' => NULL,
                'price' => '61800.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 5,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 2 visa package',
                'description' => NULL,
                'price' => '75000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 5,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 1 visa package',
                'description' => NULL,
                'price' => '69300.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 2 visa package',
                'description' => NULL,
                'price' => '84000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 3 visa package',
                'description' => NULL,
                'price' => '105000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'office' => 'Virtual Office',
                'name' => 'All-inclusive 4 visa package',
                'description' => NULL,
                'price' => '121800.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 13:18:04',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '25000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:07:13',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '42500.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:07:29',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '60000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:07:43',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '75000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:07:58',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '105000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:08:08',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '25000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:08:19',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '42500.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:08:49',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '60000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:08:59',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '75000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:09:11',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 2 visa package - Serviced Office A ',
                'description' => NULL,
                'price' => '105000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:09:23',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '34000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:09:44',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '57800.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:09:56',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '81600.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:10:32',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '102000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:10:36',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '142800.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:10:40',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '34000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:10:45',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '57800.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:10:49',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '81600.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:10:53',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '102000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:10:58',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'office' => 'Standard Office',
                'name' => 'All-inclusive 4 visa package - Serviced Office B',
                'description' => NULL,
                'price' => '142800.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:11:06',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '48000.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '81600.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '114100.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '142350.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '198850.00',
                'status' => 1,
                'visa_package' => 1,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '48000.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '81600.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '114100.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '142350.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '198850.00',
                'status' => 1,
                'visa_package' => 2,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '48000.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '81600.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '114100.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '142350.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '198850.00',
                'status' => 1,
                'visa_package' => 3,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '48000.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 1,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '81600.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 2,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '114100.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 3,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '142350.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 4,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'office' => 'Executive Office',
                'name' => 'All-inclusive 8 Visa package - Executive Office',
                'description' => NULL,
                'price' => '198850.00',
                'status' => 1,
                'visa_package' => 4,
                'license_validity' => 6,
                'freezone_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-03-11 15:49:58',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}