# version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groae-app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=groae_db
      - DB_USERNAME=groae
      - DB_PASSWORD=YIY7EFuiuYvkB0v
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: groae-mysql
    environment:
      MYSQL_ROOT_PASSWORD: YIY7EFuiuYvkB0b
      MYSQL_DATABASE: groae_db
      MYSQL_USER: groae
      MYSQL_PASSWORD: YIY7EFuiuYvkB0v
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: groae-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network


volumes:
  db-data:

networks:
  app-network:
    driver: bridge
